
CREATE TABLE `results` (
  `version` varchar(8) CHARACTER SET latin1 NOT NULL,
  `timestamp` timestamp NOT NULL,
	`used` int(11) NOT NULL DEFAULT '1',
	`lastUsed` timestamp NOT NULL,
  `ip` varchar(16) CHARACTER SET latin1 NOT NULL,
  `uniqueid` varchar(20) CHARACTER SET latin1 NOT NULL,
  `browserName` varchar(64) CHARACTER SET latin1 NOT NULL,
  `browserChannel` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `browserVersion` varchar(20) CHARACTER SET latin1 NOT NULL,
  `browserVersionType` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `browserVersionMajor` varchar(8) CHARACTER SET latin1 NOT NULL DEFAULT '' COMMENT '		',
  `browserVersionMinor` varchar(8) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `browserVersionOriginal` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `browserMode` varchar(8) CHARACTER SET latin1 NOT NULL,
  `engineName` varchar(60) CHARACTER SET latin1 NOT NULL,
  `engineVersion` varchar(20) CHARACTER SET latin1 NOT NULL,
  `osName` varchar(64) CHARACTER SET latin1 NOT NULL,
  `osVersion` varchar(20) CHARACTER SET latin1 NOT NULL,
  `deviceManufacturer` varchar(60) CHARACTER SET latin1 NOT NULL,
  `deviceModel` varchar(64) CHARACTER SET latin1 NOT NULL,
  `deviceType` varchar(16) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `deviceIdentified` int(11) NOT NULL DEFAULT '0',
  `useragent` text CHARACTER SET latin1 NOT NULL,
  `useragentHeader` text NOT NULL,
  `useragentId` char(32) NOT NULL DEFAULT '',
  `humanReadable` varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  `orientationData` mediumtext,
  PRIMARY KEY (`uniqueid`),
  UNIQUE KEY `uniqueid` (`uniqueid`),
  KEY `timestamp` (`timestamp`) USING BTREE,
  KEY `useragent` (`useragent`(20)) USING BTREE,
  KEY `version` (`version`) USING BTREE,
  KEY `useragentHeader` (`useragentHeader`(20)) USING BTREE,
  KEY `useragentId` (`useragentId`) USING BTREE,
  KEY `osName` (`osName`) USING BTREE,
  KEY `osVersion` (`osVersion`) USING BTREE,
  KEY `browserName` (`browserName`) USING BTREE,
  KEY `deviceManufacturerModel` (`deviceManufacturer`,`deviceModel`) USING BTREE,
  KEY `deviceModel` (`deviceModel`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
